tasks:
  - init: |
      echo Welcome to FIWARE
      ./services create
    command: |
      docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
      (gp ports list 2> /dev/null) || true
      ./services start
ports:
  - name: Orion
    description: Context Broker
    port: 1026
    onOpen: notify
  - name: Wilma (Orion)
    description: PEP Proxy
    port: 1027
    onOpen: ignore
    visibility: public
  - name: Node-RED
    description: Flow-programming automation
    port: 1880
    onOpen: notify
    visibility: public
  - name: Tutorial App
    description: Web app displaying context data
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: Tutorial Devices
    description: Dummy IoT Sensors over HTTP
    port: 3001
    onOpen: ignore
  - name: Keyrock
    description: Identity Manager
    port: 3005
    onOpen: open-preview
    visibility: public
  - name: MySQL
    description: Database for Keyrock
    port: 3306
    onOpen: ignore
  - name: IoT Agent (North Port)
    description: NGSI data and device provisioning
    port: 4041
    onOpen: ignore
  - name: IoT Agent (South Port)
    description: Ultralight HTTP measures
    port: 7896
    onOpen: ignore
  - name: Express
    description: Web application
    port: 8000
    onOpen: notify
  - name: Wilma (Express)
    description: Express PEP Proxy
    port: 8001
    onOpen: ignore
    visibility: public
  - name: MongoExpress
    description: MongoDB frontend
    port: 8081
    onOpen: ignore
    visibility: public
  - name: MongoDB
    description: Database for Orion + IoT Agent
    port: 27017
    onOpen: ignore
